In [23]:
import numpy as np
import requests

API_URL = "https://api-inference.huggingface.co/models/wu981526092/Token-Level-Race-Bias-Detector"
headers = {"Authorization": "Bearer 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"}

def query(API_URL,header,payload):
	response = requests.post(API_URL, headers=headers, json=payload)
	return response.json()

input_text = ["My name is Sarah Jessica Parker but you can call me Jessica","test1","test2"]
payload = {"inputs": input_text}
output = query(API_URL,headers,payload)

In [24]:
output

[[{'entity_group': 'unrelated',
   'score': 0.9936848282814026,
   'word': 'my name is',
   'start': 0,
   'end': 10},
  {'entity_group': 'stereotype',
   'score': 0.5081855058670044,
   'word': 'sarah',
   'start': 11,
   'end': 16},
  {'entity_group': 'unrelated',
   'score': 0.5035849213600159,
   'word': 'jessica',
   'start': 17,
   'end': 24},
  {'entity_group': 'stereotype',
   'score': 0.629548966884613,
   'word': 'parker',
   'start': 25,
   'end': 31},
  {'entity_group': 'unrelated',
   'score': 0.9853911399841309,
   'word': 'but you can call me',
   'start': 32,
   'end': 51},
  {'entity_group': 'stereotype',
   'score': 0.5062941312789917,
   'word': 'jessica',
   'start': 52,
   'end': 59}],
 [{'entity_group': 'unrelated',
   'score': 0.89484041929245,
   'word': 'test1',
   'start': 0,
   'end': 5}],
 [{'entity_group': 'unrelated',
   'score': 0.8839137554168701,
   'word': 'test2',
   'start': 0,
   'end': 5}]]

In [10]:
output

[{'entity_group': 'unrelated',
  'score': 0.9537973999977112,
  'word': 'my name is sarah jessica parker but you can call me',
  'start': 0,
  'end': 51},
 {'entity_group': 'stereotype_gender',
  'score': 0.5591049194335938,
  'word': 'jessica',
  'start': 52,
  'end': 59}]

In [19]:
import datasets
import numpy as np

dataset = datasets.load_dataset("wu981526092/Multidimensional_Multilevel_Bias_Classification")

Found cached dataset csv (/Users/zekunwu/.cache/huggingface/datasets/wu981526092___csv/wu981526092--Multidimensional_Multilevel_Bias_Classification-ca70dd1a187d4f9e/0.0.0/6954658bab30a358235fa864b05cf819af0e179325c740e4bc853bcc7ec513e1)


  0%|          | 0/2 [00:00<?, ?it/s]

In [22]:
np.unique(dataset["test"]["bias_type"],return_counts=True)

(array(['age', 'disability', 'gender', 'nationality',
        'physical-appearance', 'profession', 'race', 'race-color',
        'religion', 'sexual-orientation', 'socioeconomic'], dtype='<U19'),
 array([  35,   24, 1316,   64,   25, 3882, 4717,  206,  429,   34,   69]))

In [23]:
np.unique(dataset["train"]["bias_type"],return_counts=True)

(array(['age', 'disability', 'gender', 'nationality',
        'physical-appearance', 'profession', 'race', 'race-color',
        'religion', 'sexual-orientation', 'socioeconomic'], dtype='<U19'),
 array([  139,    96,  5265,   254,   101, 15528, 18866,   826,  1716,
          134,   275]))

In [7]:
dataset["train"]

In [27]:
from training.dataloader import load_data_local

In [28]:
intrasentence_dataset = load_data_local("intrasentence", marked=False)

In [45]:
from training.preprocessing import prepare_MD_SL_data

new_data = prepare_MD_SL_data(intrasentence_dataset)

In [48]:
labellist = []
for x in new_data:
	labellist.append(x['label'])

np.unique(labellist,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([8498, 1026, 1026, 3938, 3938, 3208, 3208,  326,  326]))

In [ ]:
import pandas as pd
from datasets import Dataset
from transformers import AutoTokenizer,AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer

model_path ='distilbert-base-uncased'


tokenizer = AutoTokenizer.from_pretrained(model_path)

def tokenize_function(examples):
	return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=512)

# Convert the list of dictionaries into a datasets object


temp_data = Dataset.from_pandas(pd.DataFrame(new_data))

# Tokenize the datasets
tokenized_datasets = temp_data.map(tokenize_function, batched=True)

# Convert the 'label' column to a list
tokenized_datasets = tokenized_datasets.map(lambda examples: {'labels': [examples['label']]})
final_dataset = tokenized_datasets.train_test_split(test_size=0.2, shuffle=True, seed = seed)